# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Fabric Properties
# check these on https://fabricmc.net/develop and https://repo.codemc.io/#browse/browse:relativitymc:org%2Frelativitymc%2Fmodern-yarn
minecraft_version=26.2
yarn_mappings=26.2+build.1
loader_version=0.19.3

# Mod Properties
mod_version=0.0.2-b2+mc26.2
maven_group=io.github.eat-ram.cntrafficsymbols
archives_base_name=cntrafficsymbols_core

# Dependencies
fabric_api_version=0.152.1+26.2
